import Head from "next/head";
import styles from "../styles/Home.module.css";
import CardWithIllustration from "../componenets/CardWithIllustration";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Daily-Exercise-Reminder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../pictures/logoish.webp" />
      </Head>

      <main>
        <CardWithIllustration />
      </main>

      <footer className={styles.footer}>
        <center>Powered by mailchimp</center>
      </footer>
    </div>
  );
}
